In [1]:
import sys
sys.path.append("../../")
import os
import papermill as pm
from tempfile import TemporaryDirectory

import tensorflow as tf
import warnings
warnings.filterwarnings("ignore")

from reco_utils.common.constants import SEED
from reco_utils.recommender.deeprec.deeprec_utils import (
    download_deeprec_resources, prepare_hparams
)
from reco_utils.recommender.deeprec.models.xDeepFM import XDeepFMModel
from reco_utils.recommender.deeprec.io.iterator import FFMTextIterator

print("System version: {}".format(sys.version))
print("Tensorflow version: {}".format(tf.__version__))

tmpdir = TemporaryDirectory()

System version: 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Tensorflow version: 1.15.2

In [2]:
EPOCHS_FOR_SYNTHETIC_RUN = 15
#EPOCHS_FOR_CRITEO_RUN = 30
BATCH_SIZE_SYNTHETIC = 128
#BATCH_SIZE_CRITEO = 4096
RANDOM_SEED = SEED  # Set None for non-deterministic result

In [3]:
data_path = tmpdir.name
yaml_file = os.path.join(data_path, r'xDeepFM.yaml')
train_file = r'foodfmtrain'
valid_file =  r'foodfmvalid'
test_file = r'foodfmtest'
predictfile = r'foodTest'

if not os.path.exists(yaml_file):
    download_deeprec_resources(r'https://recodatasets.blob.core.windows.net/deeprec/', data_path, 'xdeepfmresources.zip')

100%|██████████| 10.3k/10.3k [00:01<00:00, 7.46kKB/s]

In [4]:
yaml_file

'/var/folders/gd/f1pg0x2s5wsf5jymdrnz61nh0000gn/T/tmpgygviacl/xDeepFM.yaml'

In [5]:
hparams = prepare_hparams(yaml_file, 
                          FEATURE_COUNT=1030, 
                          FIELD_COUNT=2, 
                          cross_l2=0.0001, 
                          embed_l2=0.0001, 
                          learning_rate=0.001, 
                          epochs=EPOCHS_FOR_SYNTHETIC_RUN,
                          batch_size=BATCH_SIZE_SYNTHETIC)
print(hparams)

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

kg_file=None,user_clicks=None,FEATURE_COUNT=1030,FIELD_COUNT=2,data_format=ffm,PAIR_NUM=None,DNN_FIELD_NUM=None,n_user=None,n_item=None,n_user_attr=None,n_item_attr=None,iterator_type=None,SUMMARIES_DIR=None,MODEL_DIR=None,wordEmb_file=None,entityEmb_file=None,contextEmb_file=None,news_feature_file=None,user_history_file=None,use_context=None,doc_size=None,word_size=None,entity_size=None,entity_dim=None,entity_embedding_method=None,transform=None,train_ratio=None,dim=10,layer_sizes=[100, 100],cross_layer_sizes=[1],cross_layers=None,activation=['relu', 'relu'],cross_activation=identity,user_dropout=False,dropout=[0.0, 0.0],attention_layer_sizes=None,attention_activation=None,attention_dropout=0.0,model_type=xDeepFM,method=classification,load_saved_model=False,load_model_name=you model path,filter_sizes=None,num_filters=None,mu=None,fast_CIN_d=0,use_Linear_part=False,use_FM_part=False,use_CIN_part=True,use_DNN_part=False,init_method=tnormal,init_value=0.3,embed_l2=0.0001,embed_l1=0.0,layer_l2=0.0001,layer_l1=0.0,cross_l2=0.0001,cross_l1=0.0,reg_kg=0.0,learning_rate=0.001,lr_rs=1,lr_kg=0.5,kg_training_interval=5,max_grad_norm=2,is_clip_norm=0,dtype=32,loss=log_loss,optimizer=adam,epochs=15,batch_size=128,enable_BN=False,show_step=200000,save_model=False,save_epoch=2,metrics=['auc', 'logloss'],write_tfevents=False,item_embedding_dim=None,cate_embedding_dim=None,user_embedding_dim=None,train_num_ngs=4,need_sample=True,embedding_dropout=0.3,user_vocab=None,item_vocab=None,cate_vocab=None,pairwise_metrics=None,EARLY_STOP=100,max_seq_length=None,hidden_size=None,L=None,T=None,n_v=None,n_h=None,min_seq_length=1,attention_size=None,att_fcn_layer_sizes=None,dilations=None,kernel_size=None,embed_size=None,n_layers=None,decay=None,eval_epoch=None,top_k=None

In [6]:
#input_creator = FFMTextIterator

In [6]:
model = XDeepFMModel(hparams, FFMTextIterator, seed=RANDOM_SEED)

# check the predictive performance before the model is trained
print(model.run_eval(test_file)) 
model.fit(train_file, valid_file)
# check the predictive performance after the model is trained
res_real = model.run_eval(test_file)
print(res_real)
pm.record("res_real", res_real)

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:28: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/io/iterator.py:50: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/xDeepFM.py:32: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/xDeepFM.py:34: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

Add CIN part.
WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/xDeepFM.py:199: The name tf.matrix_band_part is deprecated. Please use tf.linalg.band_part instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/xDeepFM.py:199: The name tf.diag is deprecated. Please use tf.linalg.tensor_diag instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/xDeepFM.py:277: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:205: The name tf.losses.log_loss is deprecated. Please use tf.compat.v1.losses.log_loss instead.

WARNING:tensorflow:From /Users/shubh/opt/anaconda3/envs/reco_base/lib/python3.6/site-packages/tensorflow_core/python/ops/losses/losses_impl.py:121: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:55: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:259: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:57: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:57: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:58: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:107: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:110: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:62: The name tf.GPUOptions is deprecated. Please use tf.compat.v1.GPUOptions instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:63: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/models/base_model.py:64: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From ../../reco_utils/recommender/deeprec/io/iterator.py:113: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

{'auc': 0.509, 'logloss': 0.693}
at epoch 1
train info: logloss loss:0.7199932344352142
eval info: auc:0.4929, logloss:0.6878
at epoch 1 , train time: 0.4 eval time: 0.4
at epoch 2
train info: logloss loss:0.7061250006096272
eval info: auc:0.4936, logloss:0.6838
at epoch 2 , train time: 0.2 eval time: 0.3
at epoch 3
train info: logloss loss:0.6961172713509088
eval info: auc:0.4944, logloss:0.6811
at epoch 3 , train time: 0.2 eval time: 0.3
at epoch 4
train info: logloss loss:0.6880952225455755
eval info: auc:0.4956, logloss:0.6795
at epoch 4 , train time: 0.2 eval time: 0.3
at epoch 5
train info: logloss loss:0.6794489071338992
eval info: auc:0.4969, logloss:0.6793
at epoch 5 , train time: 0.3 eval time: 0.3
at epoch 6
train info: logloss loss:0.6664385290085515
eval info: auc:0.4987, logloss:0.6813
at epoch 6 , train time: 0.3 eval time: 0.3
at epoch 7
train info: logloss loss:0.6455026585844499
eval info: auc:0.5001, logloss:0.6878
at epoch 7 , train time: 0.3 eval time: 0.3
at epoch 8
train info: logloss loss:0.61588723825503
eval info: auc:0.5009, logloss:0.702
at epoch 8 , train time: 0.3 eval time: 0.3
at epoch 9
train info: logloss loss:0.5808832302123685
eval info: auc:0.5015, logloss:0.7258
at epoch 9 , train time: 0.3 eval time: 0.3
at epoch 10
train info: logloss loss:0.5454600347748285
eval info: auc:0.5019, logloss:0.7582
at epoch 10 , train time: 0.2 eval time: 0.3
at epoch 11
train info: logloss loss:0.5129573922368544
eval info: auc:0.5019, logloss:0.7962
at epoch 11 , train time: 0.2 eval time: 0.3
at epoch 12
train info: logloss loss:0.48437517598459995
eval info: auc:0.5021, logloss:0.837
at epoch 12 , train time: 0.2 eval time: 0.4
at epoch 13
train info: logloss loss:0.4594515479063686
eval info: auc:0.5023, logloss:0.879
at epoch 13 , train time: 0.4 eval time: 0.3
at epoch 14
train info: logloss loss:0.4375932656134231
eval info: auc:0.5025, logloss:0.9213
at epoch 14 , train time: 0.2 eval time: 0.3
at epoch 15
train info: logloss loss:0.41824517012396945
eval info: auc:0.5025, logloss:0.9637
at epoch 15 , train time: 0.2 eval time: 0.3
{'auc': 0.4951, 'logloss': 0.9621}

In [7]:
model.predict(predictfile, "fmfoodlargetestfile.txt")
?model.predict

Signature: model.predict(infile_name, outfile_name)
Docstring:
Make predictions on the given data, and output predicted scores to a file.

Args:
    infile_name (str): Input file name, format is same as train/val/test file.
    outfile_name (str): Output file name, each line is the predict score.

Returns:
    obj: An instance of self.
File:      ~/ADM/Assignment3-Recommender System/reco_utils/recommender/deeprec/models/base_model.py
Type:      method

In [9]:
# import pickle
# pickle.dump(model, open("abc.pickle", 'wb'))

In [10]:
# type(model)

In [11]:
# import joblib
# import pickle
# joblib.dump(model, 'model.joblib')

In [8]:
import pandas as pd

In [9]:
prediction_df = pd.read_fwf('fmfoodlargetestfile.txt',header=None)

In [18]:
prediction_df.columns = ["Like Probability"]

In [19]:
prediction_df

       Like Probability
0              0.271233
1              0.022452
2              0.011625
3              0.057317
4              0.121535
...                 ...
29995          0.614679
29996          0.228405
29997          0.499540
29998          0.315276
29999          0.712102

[30000 rows x 1 columns]

In [14]:
prediction_df1 = prediction_df.copy()

In [15]:
prediction_df1['Like Probability'] = prediction_df1['Like Probability'].round(decimals=3)

In [16]:
prediction_df1

       Like Probability
0                 0.271
1                 0.022
2                 0.012
3                 0.057
4                 0.122
...                 ...
29995             0.615
29996             0.228
29997             0.500
29998             0.315
29999             0.712

[30000 rows x 1 columns]

In [20]:
data_df = pd.read_csv("datatopredict.csv")
data_df

       Unnamed: 0  userId  productId  ratings
0               0     411        115        1
1               1     244        122        0
2               2     755        102        0
3               3     391        126        0
4               4     778        109        1
...           ...     ...        ...      ...
29995       29995     367        109        0
29996       29996     524        129        0
29997       29997     794        101        0
29998       29998     314        116        1
29999       29999     615        106        0

[30000 rows x 4 columns]

In [21]:
data_df1= data_df[["userId","productId"]]
data_df1

       userId  productId
0         411        115
1         244        122
2         755        102
3         391        126
4         778        109
...       ...        ...
29995     367        109
29996     524        129
29997     794        101
29998     314        116
29999     615        106

[30000 rows x 2 columns]

In [22]:
result = pd.concat([data_df1, prediction_df1], axis=1, join='inner')

In [23]:
result

       userId  productId  Like Probability
0         411        115             0.271
1         244        122             0.022
2         755        102             0.012
3         391        126             0.057
4         778        109             0.122
...       ...        ...               ...
29995     367        109             0.615
29996     524        129             0.228
29997     794        101             0.500
29998     314        116             0.315
29999     615        106             0.712

[30000 rows x 3 columns]

In [24]:
result2 = result.copy()

In [25]:
food_df = pd.read_csv("FoodDetails.csv")

In [26]:
food_df

    productId   Product Name  Price
0         116          Salad      6
1         121           Milk      9
2         126           Tuna      5
3         109        Cupcake      9
4         124        Carrots     10
5         105           Meat     15
6         110     Curly Kale      5
7         111        Cereals      5
8         101          Bread     11
9         100          Juice      6
10        107         Banana     15
11        103         Cheese      6
12        104         Cookie      5
13        118           Curd     13
14        108         Grapes      7
15        120           Eggs      8
16        129        Avocado      6
17        123          Chips     14
18        128  coconut water     15
19        125      Zhucchini      6
20        113         walnut     14
21        127          pizza      8
22        115        Cabbage      5
23        106           Fish      5
24        119        Cereals     14
25        102      Sphagetti     14
26        112           Rice     11
27        114         Apples      9
28        122       Tortilla      6
29        117         Frozen      8

In [27]:
img = ['https://adm-food-probability.s3.amazonaws.com/salad.jpg',
      'https://adm-food-probability.s3.amazonaws.com/milk.jpg',
      'https://adm-food-probability.s3.amazonaws.com/tuna.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cupcakes.jpg',
      'https://adm-food-probability.s3.amazonaws.com/carrots.jpg',
       'https://adm-food-probability.s3.amazonaws.com/meat.jpg',
      'https://adm-food-probability.s3.amazonaws.com/curlykale.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cereal.jpg',
      'https://adm-food-probability.s3.amazonaws.com/bread.jpg',
      'https://adm-food-probability.s3.amazonaws.com/juice.jpg',
      'https://adm-food-probability.s3.amazonaws.com/banana.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cheese.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cookie.jpg',
      'https://adm-food-probability.s3.amazonaws.com/curd.jpg',
      'https://adm-food-probability.s3.amazonaws.com/grapes.jpg',
      'https://adm-food-probability.s3.amazonaws.com/eggs.jpg',
      'https://adm-food-probability.s3.amazonaws.com/avocado.jpg',
      'https://adm-food-probability.s3.amazonaws.com/chips.jpg',
      'https://adm-food-probability.s3.amazonaws.com/coconut water.jpg',
      'https://adm-food-probability.s3.amazonaws.com/zuccini.jpg',
      'https://adm-food-probability.s3.amazonaws.com/walnut.jpg',
      'https://adm-food-probability.s3.amazonaws.com/pizza.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cabbage.jpg',
      'https://adm-food-probability.s3.amazonaws.com/fish.jpg',
      'https://adm-food-probability.s3.amazonaws.com/cereals.jpg',
      'https://adm-food-probability.s3.amazonaws.com/spaghetti.jpg',
      'https://adm-food-probability.s3.amazonaws.com/rice.jpg',
      'https://adm-food-probability.s3.amazonaws.com/apple.jpg',
      'https://adm-food-probability.s3.amazonaws.com/tortilla.jpg',
      'https://adm-food-probability.s3.amazonaws.com/frozen.jpg']

In [30]:
food_df['img']=img

In [31]:
xdeepfmfinal = pd.merge(result2,food_df, on='productId')

In [33]:
xdeepfmfinal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29000 entries, 0 to 28999
Data columns (total 6 columns):
userId              29000 non-null int64
productId           29000 non-null int64
Like Probability    29000 non-null float64
Product Name        29000 non-null object
Price               29000 non-null int64
img                 29000 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 1.5+ MB

In [34]:
xdeepfmfinal["userId"] = xdeepfmfinal["userId"].astype(str)
xdeepfmfinal["productId"] = xdeepfmfinal["productId"].astype(str)

In [35]:
xdeepfmfinal = xdeepfmfinal.sort_values(['Like Probability'], ascending=False)

In [36]:
xdeepfmfinal

,userId,productId,Like Probability,Product Name,Price,img
4265,91,109,1.000,Cupcake,9,https://adm-food-probability.s3.amazonaws.com/...
1287,124,122,1.000,Tortilla,6,https://adm-food-probability.s3.amazonaws.com/...
2724,991,102,0.999,Sphagetti,14,https://adm-food-probability.s3.amazonaws.com/...
13867,991,105,0.998,Meat,15,https://adm-food-probability.s3.amazonaws.com/...
15969,884,104,0.998,Cookie,5,https://adm-food-probability.s3.amazonaws.com/...
...,...,...,...,...,...,...
2236,859,102,0.001,Sphagetti,14,https://adm-food-probability.s3.amazonaws.com/...
6715,872,108,0.001,Grapes,7,https://adm-food-probability.s3.amazonaws.com/...
4286,884,109,0.000,Cupcake,9,https://adm-food-probability.s3.amazonaws.com/...
3440,902,126,0.000,Tuna,5,https://adm-food-probability.s3.amazonaws.com/...
2530,872,102,0.000,Sphagetti,14,https://adm-food-probability.s3.amazonaws.com/...

In [37]:
(xdeepfmfinal[xdeepfmfinal["userId"] == "2"]).sort_values(by='Like Probability', ascending=False).reset_index(drop=True).loc[0:4,:]

,userId,productId,Like Probability,Product Name,Price,img
0,2,105,0.931,Meat,15,https://adm-food-probability.s3.amazonaws.com/...
1,2,115,0.929,Cabbage,5,https://adm-food-probability.s3.amazonaws.com/...
2,2,126,0.918,Tuna,5,https://adm-food-probability.s3.amazonaws.com/...
3,2,120,0.877,Eggs,8,https://adm-food-probability.s3.amazonaws.com/...
4,2,102,0.766,Sphagetti,14,https://adm-food-probability.s3.amazonaws.com/...

In [ ]:
import pickle
pickle.dump(xdeepfmfinal, open("xdeepfmfinalimage.pkl", 'wb'))